FROM alpine:3.17

ENV CLI_VERSION 0.0.35


RUN apk update && \
    wget "https://github.com/nats-io/natscli/releases/download/v${CLI_VERSION}/nats-${CLI_VERSION}-linux-amd64.zip" && \
    unzip -p nats-${CLI_VERSION}-linux-amd64.zip nats-${CLI_VERSION}-linux-amd64/nats > /usr/local/bin/nats && \
    chmod +x /usr/local/bin/nats && \
    rm "nats-${CLI_VERSION}-linux-amd64.zip"

ENTRYPOINT ["nats"]
